### ISSUE TITLE
ODM Schema Compile problems

### ISSUE THREAD

**Issue by jinjingfarm** [InterPSS-Project/ipss-odm#14]
After generating the Java classes with JAXB, there are few classes with compile errors:

DStabBusXmlType.java,
DStabGenDataXmlType.java,
DStabLoadDataXmlType, 
...

**Comment by jinjingfarm** [comment]
@thuang  with the new commit https://github.com/InterPSS-Project/ipss-odm/commit/4b1be9109a124c8a85a6c018c363b1d0077cd55e I am still having the compile problems.

**Comment by jinjingfarm** [comment]
@thuang have you merge all your changes to the master branch?

**Comment by thuang** [comment]
For the ODM part, yes. Could you show more details of the compile issues?

**Comment by jinjingfarm** [comment]
A new branch https://github.com/InterPSS-Project/ipss-odm/tree/investigation_06132018 has been created for the investigation

**Comment by jinjingfarm** [comment]
@thuang I assume that you do not see any compile error at your side. Please take a look at the https://github.com/InterPSS-Project/ipss-odm/tree/investigation_06132018/ieee.odm.schema/temp/notes.txt, the put your generated code in this dir for comparison.

**Comment by jinjingfarm** [comment]
@thuang  please upload your generated Java files https://github.com/InterPSS-Project/ipss-odm/tree/master/ieee.odm.schema/src/org/ieee/odm/schema

**Comment by jinjingfarm** [comment]
It seems that the problem is caused by the Eclipse neon.3 IDE. I changed to Eclipse Photon, the issue was resolved automatically.
